//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePermissionSlips.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianApproval
    {
        public int PermissionSlipID { get; set; }
        public int StudentID { get; set; }
        public string GuardianName { get; set; }
        public string GuardianEmail { get; set; }
        public bool CanChaperone { get; set; }
        public string SpecialHealthDietaryAccessConsiderations { get; set; }
        public string DaytimePhone { get; set; }
        public string EmergencyPhone { get; set; }
        public byte[] Signature { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public string GuardianUserID { get; set; }
        public bool Approved { get; set; }
    
        public virtual PermissionSlip PermissionSlip { get; set; }
        public virtual Student Student { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
