//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePermissionSlips.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianPermissionSlipsView
    {
        public int SchoolID { get; set; }
        public string SchoolName { get; set; }
        public string UserID { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public bool EmailConfirmed { get; set; }
        public string PhoneNumber { get; set; }
        public string RoleName { get; set; }
        public int ClassID { get; set; }
        public string RoomNumber { get; set; }
        public string TeacherUserID { get; set; }
        public int EventID { get; set; }
        public string EventName { get; set; }
        public string EventLocation { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal Cost { get; set; }
        public bool RequireChaperone { get; set; }
        public bool RequireChaperoneBackgroundCheck { get; set; }
        public Nullable<bool> Approved { get; set; }
        public string GuardianName { get; set; }
        public Nullable<bool> CanChaperone { get; set; }
        public string SpecialHealthDietaryAccessConsiderations { get; set; }
        public string DaytimePhone { get; set; }
        public string EmergencyPhone { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public byte[] GuardianApprovalSignature { get; set; }
        public string StudentName { get; set; }
        public string ClassName { get; set; }
        public int StudentID { get; set; }
    }
}
