//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePermissionSlips.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PermissionSlip
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionSlip()
        {
            this.GuardianApprovals = new HashSet<GuardianApproval>();
        }
    
        public int ID { get; set; }
        public Nullable<int> PermissionSlipTemplateID { get; set; }
        public int ClassRoomID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public System.DateTime StartDateTime { get; set; }
        public System.DateTime EndDateTime { get; set; }
        public decimal Cost { get; set; }
        public bool RequireChaperone { get; set; }
        public bool RequireChaperoneBackgroundCheck { get; set; }
        public int PermissionSlipCategoryID { get; set; }
    
        public virtual ClassRoom ClassRoom { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuardianApproval> GuardianApprovals { get; set; }
        public virtual Template Template { get; set; }
        public virtual Category Category { get; set; }
    }
}
