//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePermissionSlips.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemConfiguration
    {
        public int Id { get; set; }
        public string EmailDomain { get; set; }
        public string EmailAPIKey { get; set; }
        public string DefaultFromAddress { get; set; }
    }
}
