//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlinePermissionSlips.Models.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Template
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Template()
        {
            this.PermissionSlips = new HashSet<PermissionSlip>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Location { get; set; }
        public Nullable<decimal> Cost { get; set; }
        public bool RequireChaperone { get; set; }
        public bool RequireChaperoneBackgroundCheck { get; set; }
        public Nullable<System.DateTime> DisabledDateTime { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public System.DateTime ModifiedDateTime { get; set; }
        public byte[] ConsistencyCheck { get; set; }
        public int CategoryID { get; set; }
        public Nullable<int> SchoolID { get; set; }
        public Nullable<int> ClassRoomID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionSlip> PermissionSlips { get; set; }
        public virtual Category Category { get; set; }
        public virtual ClassRoom ClassRoom { get; set; }
        public virtual School School { get; set; }
    }
}
